version: 0.0
os: linux

files:
  - source: /
    desination: /home/ubuntu/sungkyu/front
    overwrite: yes

permissions:
  - object: /home/ubuntu
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: root