version: 0.0
os: linux

files:
  - source: /
    desination: /home/ubuntu/test
    overwrite: yes

permissions:
  - object: /home/ubuntu
    owner: root
    group: root
    mode: 755

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: root