# This is a basic workflow to help you get started with Actions

name: front

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ./front

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Check Node v
        run: node -v        
        
      - name: install dependency
        run: npm install --frozen-lockfile
        
      - name: build
        run: npm run build
        
      - name: zip create
        run: zip -qq -r ./buildfe.zip .
        shell: bash
        
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
          
      - name: upload to s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
          
        run: |
          aws s3 cp --region ap-northeast-2 ./buildfe.zip s3://sungkyu.info/deploy/buildfe.zip
          
      - name: deploy
        run: aws deploy create-deployment
          --application-name sungkyu-blog-front
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name GROUP
          --s3-location bucket=sungkyu.info,key=deploy/buildfe.zip,bundleType=zip
